//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.Tax.SST.Gateway.DB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ack
    {
        public string identity { get; set; }
        public string id { get; set; }
        public string transmitter { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string data { get; set; }
        public string createdonhostname { get; set; }
        public string version { get; set; }
        public Nullable<bool> processed { get; set; }
    }
}
