//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.Tax.SST.Gateway.DB.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sstpEntities : DbContext
    {
        public sstpEntities()
            : base("name=sstpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ack> acks { get; set; }
        public DbSet<batch> batches { get; set; }
        public DbSet<config> configs { get; set; }
        public DbSet<receipt> receipts { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<sstpid> sstpids { get; set; }
        public DbSet<transmission> transmissions { get; set; }
        public DbSet<user> users { get; set; }
    }
}
