//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.Tax.SST.Gateway.DB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role
    {
        public string username { get; set; }
        public string role { get; set; }
    }
}
